name = "HigherOrderNetworks"
uuid = "6f6a334d-9044-495a-bc2b-8b1543872cbf"
authors = ["Nicole Eikmeier <eikmeier@grinnell.edu>", "Josh Turner <turnerjo@grinnell.edu>", "Charun Upara <uparacha@grinnell.edu>"]
version = "0.1.0"

[deps]
MatrixNetworks = "4f449596-a032-5618-b826-5a251cb6dc11"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
